name: clocking-server-checker

on:
  push:

permissions: {}

jobs:
  rust-checker:
    runs-on: ubuntu-latest
    steps:
      - name: rust-checker-actions
        uses: ./.github/actions/rust-checker
        with:
          directory: "clocking-server"
