name: social-server-checker

on:
  push:

permissions: {}

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo-fmt
        uses: ./.github/actions/cargo-fmt
        with:
          directory: "social-server"

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo-clippy
        uses: ./.github/actions/cargo-clippy
        with:
          directory: "social-server"

  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo-test
        uses: ./.github/actions/cargo-test
        with:
          directory: "social-server"
